### PR TITLE
Remove 404 from ignored HTTP status codes

### PR DESCRIPTION
**Pull request by contolini**
NR ignores 404 errors by default. We'd like to start tracking them. See https://discuss.newrelic.com/t/how-to-track-404-requests/1406

### CODE REVIEW

**Comment by OrlandoSoto** [comment]
👍

**Comment by OrlandoSoto** [comment]
thanks @contolini !

**Comment by jonathanwcrane** [comment]
So you're now explicitly declaring a list of ignored codes, which supercedes the default list of ignored codes, and the default list includes 404.  Is that right?

**Comment by contolini** [comment]
@jonathanwcrane Correct. When you run `newrelic-admin generate-config` it generates a file with the [default list](https://docs.newrelic.com/docs/agents/python-agent/installation-configuration/python-agent-configuration#error-ignore-status-codes). I took what it generated and removed 404.

**Comment by jonathanwcrane** [comment]
Thanks!  Good work!

**Pull request merged**
