### PR TITLE
Adding apache restart task after new_relic.ini configuration.

### PR DESCRIPTION
**Pull request by vickumar1981**
Paired with @vccabral and @marcesher

### CODE REVIEW

**Comment by vccabral** [comment]
LGTM

**Comment by sleitner** [comment]
I see why you might want to add more notifications, but I don't think restart should be a task. How do you justify restarting apache when nothing has changed? (On prod servers, too...)

**Comment by vccabral** [comment]
@sleitner when we edited the newrelic ini, it did NOT trigger an apache restart. However a restart is required for new new relic settings to take effect. If we can make the handler pickup differences to the new relic ini then we can go that route.

**Comment by sleitner** [comment]
@vccabral Right, so there probably needs to be a [notify](http://docs.ansible.com/ansible/playbooks_intro.html#handlers-running-operations-on-change) where there is not one right now. It would be much better to add 

```
  notify:
    - restart apache
```

after every task that modifies the ini. (I should have done that originally -- I didn't because I didn't imagine we'd be tweaking settings, but that was short sighted).

**Comment by m3brown** [comment]
Does `notify` in ansible work similar to puppet, where the resulting task is **only** executed if the content of the notifying task changed?  In this case I'd agree, notify sounds like a good idea here.  If we run ansible 5 times or 100 times, it should only be restarting apache the executions where the apache configuration changes, which might only be the first execution.

**Comment by sleitner** [comment]
@m3brown that's right, `notify` only runs the handler if the related task runs, and it runs that handler one time at the end of the play.

**Comment by vccabral** [comment]
Would we add a notify to each of these lines? 

https://github.com/cfpb/new-relic-installer/blob/ef1c58f6a14e9532820892c4da91acf55fe18135/provisioners/roles/newrelic_wsgi/tasks/main.yml#L30-L49

**Comment by m3brown** [comment]
Any line that potentially modifies the apache configs should have a notify.  Here's an example of how it wires together:

http://docs.ansible.com/ansible/playbooks_best_practices.html#task-and-handler-organization-for-a-role

**Comment by vccabral** [comment]
@m3brown  

After speaking with @sleitner , 1) it is not an apache config change. It is a newrelic ini config change and 2) the config is generated every time so each of those tasks is a "changed" = true. We would have to refactor the ini generation into a template and then add a notify httpd service to that new template task.

**Comment by marcesher** [comment]
Is it worth all that work?

**Comment by m3brown** [comment]
Ahh, I assumed it was a template.  If you've already confirmed "changed" is true every time, then that's kind of deal breaker.  I have a couple more questions and then I'll stop pushing:

How often does this Ansible script run? Is it manual only?

My only concern is the point that @sleitner originally brought up: We don't want to willy nilly restart apache on production servers unless we have a good reason.  If the ansible job is only going to run sporadically then this is a solution I can live with.

**Comment by marcesher** [comment]
It runs manually, not on a schedule.

So it would run when:

1) making a change to a config that we want to have pushed to an existing server (thus requiring restart)
2) when adding a new server (rare, currently), since the playbook currently runs for all servers in the inventory, not just newly added ones, by design.

**Comment by sleitner** [comment]
To clarify, (1) would cause a restart on all servers with the above change. If we don't want to expend the energy on a template file, I'd advocate for reverting to the single notify that occurs when new relic is initially provisioned, and asking anyone making a white list change to manually restart servers.

**Pull request merged**
